
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>DeathLeaderboard</AssemblyName>
    <LangVersion>latest</LangVersion>
      <DotNetPath Condition=" '$(OS)' == 'Windows_NT' ">dotnet.exe</DotNetPath>
      <DotNetPath Condition=" '$(OS)' == 'Unix' ">dotnet</DotNetPath>
      <DotNetPath Condition=" '$(DotNetPath)' == '' ">dotnet</DotNetPath>
  </PropertyGroup>
</Project>